const fs = require('fs');
const path = require('path');

const models = {
  'models/NalabheemaProfile.js': `import mongoose from 'mongoose';\n\nconst NalabheemaProfileSchema = new mongoose.Schema({\n  customerId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },\n  dietaryConstraints: [{ type: String, enum: ['VEGAN', 'KETO', 'GLUTEN_FREE', 'DIABETIC_FRIENDLY', 'HALAL', 'NONE'], default: 'NONE' }],\n  flavorProfile: { spiceTolerance: { type: Number, min: 1, max: 10, default: 5 }, sweetPreference: { type: Number, min: 1, max: 10, default: 5 } },\n  culinarySkillLevel: { type: String, enum: ['BEGINNER', 'INTERMEDIATE', 'EXPERT'], default: 'BEGINNER' },\n  favoriteRecipes: [{ recipeId: { type: mongoose.Schema.Types.ObjectId, ref: 'Recipe' }, addedAt: { type: Date, default: Date.now } }],\n  healthGoals: { targetCalories: { type: Number }, targetProteinGrams: { type: Number } },\n  voicePreference: { language: { type: String, enum: ['te-IN', 'hi-IN', 'en-IN'], default: 'te-IN' }, speed: { type: Number, default: 1.0 } }\n}, { timestamps: true });\n\nexport default mongoose.model('NalabheemaProfile', NalabheemaProfileSchema);`,

  'models/SoilTest.js': `import mongoose from 'mongoose';\n\nconst SoilTestSchema = new mongoose.Schema({\n  farmerId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },\n  location: { type: { type: String, enum: ['Point'], default: 'Point' }, coordinates: { type: [Number], required: true } },\n  source: { type: String, enum: ['SMARTPHONE_TINYML', 'LORAWAN_SENSOR', 'LABORATORY'], required: true },\n  metrics: { nitrogen_mg_kg: { type: Number }, phosphorus_mg_kg: { type: Number }, potassium_mg_kg: { type: Number }, phLevel: { type: Number }, moisturePercentage: { type: Number } },\n  visionInference: { imageHash: { type: String }, detectedAnomalies: [{ type: String }], soilTexture: { type: String, enum: ['CLAY', 'SAND', 'SILT', 'LOAM'] } },\n  aiRecommendations: [{ cropSuggested: { type: String }, fertilizerSuggested: { type: String }, confidenceScore: { type: Number } }]\n}, { timestamps: true });\n\nSoilTestSchema.index({ location: '2dsphere' });\nexport default mongoose.model('SoilTest', SoilTestSchema);`,

  'models/PackagingOptimization.js': `import mongoose from 'mongoose';\n\nconst PackagingOptimizationSchema = new mongoose.Schema({\n  routeId: { type: mongoose.Schema.Types.ObjectId, ref: 'VehicleRoute', required: true },\n  cropType: { type: String, required: true },\n  weatherData: { ambientTemperatureCelsius: { type: Number, required: true }, humidityPercentage: { type: Number } },\n  transit: { estimatedTransitTimeMins: { type: Number, required: true }, cargoWeightInertiaKg: { type: Number } },\n  recommendation: { material: { type: String, enum: ['ARECA_SHELL', 'CORRUGATED_CARDBOARD', 'BAMBOO_CRATE', 'PLA_BIOPLASTIC'], required: true }, pcmGelGramsRequired: { type: Number, required: true }, thermalDecayRiskScore: { type: Number, min: 0, max: 1 } },\n  sustainabilityMetrics: { co2SavedKg: { type: Number }, isPlasticFree: { type: Boolean, default: true } }\n}, { timestamps: true });\n\nexport default mongoose.model('PackagingOptimization', PackagingOptimizationSchema);`,

  'models/OrganicCertification.js': `import mongoose from 'mongoose';\n\nconst OrganicCertificationSchema = new mongoose.Schema({\n  cropBatchId: { type: mongoose.Schema.Types.ObjectId, ref: 'Crop', required: true },\n  farmerId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },\n  blockchain: { polygonTokenId: { type: String }, smartContractAddress: { type: String }, transactionHash: { type: String } },\n  iotOracleData: { lastSyntheticNitrogenSpikeDetected: { type: Date }, isRevokedBySensor: { type: Boolean, default: false } },\n  hyperspectralInspection: { inspectedAtHubId: { type: mongoose.Schema.Types.ObjectId, ref: 'Hub' }, inspectedAtTime: { type: Date }, pesticideResidueDetected: { type: Boolean, default: false }, svmConfidenceScore: { type: Number }, imageSpectrumHash: { type: String } },\n  certificationStatus: { type: String, enum: ['PENDING_ON_CHAIN', 'VERIFIED_ORGANIC', 'REVOKED_FRAUD', 'LAB_TEST_REQUIRED'], default: 'PENDING_ON_CHAIN' }\n}, { timestamps: true });\n\nexport default mongoose.model('OrganicCertification', OrganicCertificationSchema);`,

  'controllers/nalabheemaController.js': `import NalabheemaProfile from '../models/NalabheemaProfile.js';\n\nexport const getProfile = async (req, res) => {\n  try {\n    let profile = await NalabheemaProfile.findOne({ customerId: req.user.id });\n    if (!profile) profile = await NalabheemaProfile.create({ customerId: req.user.id });\n    res.status(200).json({ success: true, data: profile });\n  } catch (error) { res.status(500).json({ success: false, error: 'Server Error' }); }\n};\n\nexport const generateRecipe = async (req, res) => {\n  try {\n    const { ingredients } = req.body;\n    const generatedRecipe = { title: "Nalabheema Special Spicy Tomato Curry", ingredientsUsed: ingredients, instructions: ["Heat oil in a pan.", "Add mustard seeds."], macros: { calories: 250, protein: 5 } };\n    res.status(200).json({ success: true, data: generatedRecipe });\n  } catch (error) { res.status(500).json({ success: false, error: 'Server Error' }); }\n};`,

  'controllers/soilTestController.js': `import SoilTest from '../models/SoilTest.js';\n\nexport const submitTest = async (req, res) => {\n  try {\n    const testResult = await SoilTest.create({ farmerId: req.user.id, ...req.body });\n    res.status(201).json({ success: true, data: testResult });\n  } catch (error) { res.status(500).json({ success: false, error: 'Server Error' }); }\n};\n\nexport const getRegionalMap = async (req, res) => {\n  try {\n    const tests = await SoilTest.find({ location: { $near: { $geometry: { type: 'Point', coordinates: [parseFloat(req.query.lng), parseFloat(req.query.lat)] }, $maxDistance: 50000 } } });\n    res.status(200).json({ count: tests.length, data: tests });\n  } catch (error) { res.status(500).json({ success: false, error: 'Server Error' }); }\n};`,

  'controllers/packagingController.js': `import PackagingOptimization from '../models/PackagingOptimization.js';\n\nexport const calculatePackaging = async (req, res) => {\n  try {\n    const { routeId, cropType, ambientTemperatureCelsius, estimatedTransitTimeMins } = req.body;\n    let material = 'CORRUGATED_CARDBOARD', pcmGelGrams = 0;\n    if (ambientTemperatureCelsius > 35 && estimatedTransitTimeMins > 60) { material = 'PLA_BIOPLASTIC'; pcmGelGrams = (ambientTemperatureCelsius - 15) * estimatedTransitTimeMins * 0.5; }\n    const optimizationResult = await PackagingOptimization.create({ routeId, cropType, weatherData: { ambientTemperatureCelsius }, transit: { estimatedTransitTimeMins }, recommendation: { material, pcmGelGramsRequired: Math.round(pcmGelGrams), thermalDecayRiskScore: 0.1 } });\n    res.status(201).json({ success: true, data: optimizationResult });\n  } catch (error) { res.status(500).json({ success: false, error: 'Server Error' }); }\n};`,

  'controllers/organicCertController.js': `import OrganicCertification from '../models/OrganicCertification.js';\n\nexport const iotOracleWebhook = async (req, res) => {\n  try {\n    const { farmerId, cropBatchId, nitrogenLevel } = req.body;\n    if (nitrogenLevel > 500) {\n      await OrganicCertification.findOneAndUpdate({ cropBatchId }, { 'iotOracleData.lastSyntheticNitrogenSpikeDetected': Date.now(), 'iotOracleData.isRevokedBySensor': true, certificationStatus: 'REVOKED_FRAUD' }, { new: true, upsert: true });\n      return res.status(200).json({ success: true, message: 'Organic certification revoked due to chemical detection.' });\n    }\n    res.status(200).json({ success: true, message: 'Levels normal.' });\n  } catch (error) { res.status(500).json({ success: false, error: 'Server Error' }); }\n};\n\nexport const submitScan = async (req, res) => {\n  try {\n    const { cropBatchId, pesticideResidueDetected, svmConfidenceScore } = req.body;\n    const cert = await OrganicCertification.findOneAndUpdate({ cropBatchId }, { 'hyperspectralInspection.pesticideResidueDetected': pesticideResidueDetected, 'hyperspectralInspection.svmConfidenceScore': svmConfidenceScore, 'hyperspectralInspection.inspectedAtTime': Date.now(), certificationStatus: pesticideResidueDetected ? 'LAB_TEST_REQUIRED' : 'VERIFIED_ORGANIC' }, { new: true });\n    res.status(200).json({ success: true, data: cert });\n  } catch (error) { res.status(500).json({ success: false, error: 'Server Error' }); }\n};`,

  'routes/nalabheemaRoutes.js': `import express from 'express';\nimport { getProfile, generateRecipe } from '../controllers/nalabheemaController.js';\nconst router = express.Router();\nconst protect = (req, res, next) => { req.user = { id: 'mockUserId' }; next(); };\nrouter.get('/profile', protect, getProfile);\nrouter.post('/generate-recipe', protect, generateRecipe);\nexport default router;`,

  'routes/soilTestRoutes.js': `import express from 'express';\nimport { submitTest, getRegionalMap } from '../controllers/soilTestController.js';\nconst router = express.Router();\nconst protect = (req, res, next) => { req.user = { id: 'mockUserId' }; next(); };\nrouter.post('/submit', protect, submitTest);\nrouter.get('/regional-map', protect, getRegionalMap);\nexport default router;`,

  'routes/packagingRoutes.js': `import express from 'express';\nimport { calculatePackaging } from '../controllers/packagingController.js';\nconst router = express.Router();\nconst protect = (req, res, next) => { req.user = { id: 'mockUserId' }; next(); };\nrouter.post('/calculate', protect, calculatePackaging);\nexport default router;`,

  'routes/organicCertRoutes.js': `import express from 'express';\nimport { iotOracleWebhook, submitScan } from '../controllers/organicCertController.js';\nconst router = express.Router();\nconst protect = (req, res, next) => { req.user = { id: 'mockUserId', role: 'ADMIN' }; next(); };\nrouter.post('/iot-webhook', iotOracleWebhook);\nrouter.post('/hyperspectral-scan', protect, submitScan);\nexport default router;`
};

for (const [file, content] of Object.entries(models)) {
  fs.writeFileSync(path.join(process.cwd(), file), content);
}
console.log('Successfully repaired ES6 imports for all 12 files.');
